server:
  port: 8000

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/dna_forensics}
    username: ${SPRING_DATASOURCE_USERNAME:dna_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:dna_admin}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:7200000}

springdoc:
  swagger-ui:
    tagsSorter: none
    operationsSorter: none